# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deb30ca3e9994da44a020ff8ef29c28ce0ccb31b9d015ab0ba82f00b515d237343db28dd4ad160f02631cab6109780ed484a087fe5f1e03f549b39d5c145de65

test:
  secret_key_base: 493e35b99d7d743ce3596cfa58d29fd5fa217b3006ee99de69a3dc78c62e0ef7fd71298039fea9e89c0259455ce371a2727cd3f7b028ec7ce227e4ff87bb42d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
